name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # DANGER!!!! this might check out a stale commit
        ref: ${{ github.event.pull_request.merge_commit_sha }}

    - name: Use Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Test
      run: |
        yarn
        yarn test:ci

    - name: Publish Code Coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
